### PR TITLE
Migrate firebase

### PR DESCRIPTION
**Pull request by ewal**
Migrate to the latest version of Firebase and the new Firebase Console from Google. There are several steps required to do the migration so read the instruction in the migration guide carefully.

### CODE REVIEW

**Comment by himynameisjonas** [comment]
Will test this next time I'm at the computer 👍👍

**Comment by himynameisjonas** [comment]
Sorry, forgot about this 😄

**Comment by himynameisjonas** [comment]
@ewal sorry, forgot about this 😄

**Comment by ewal** [comment]
@himynameisjonas haha, no worries 😄

**Pull request closed without merging**
